public_env_variables:
    API_KEY: ENC[AES256_GCM,data:aqLThZkex7NZk9nWJJ/S0SuZowQ3T/WvPYM7QdgPv8g=,iv:OUzrReEASlY0vtMT4nlKi1LZHsZ7hZW6E1mG6YAyYLU=,tag:p5i00qwmktj3n+z+9Inikg==,type:str]    PGSQL_URI: ENC[AES256_GCM,data:EpT93Lon5qDk2kKvsGaY90yEIbhS3VndIym40En0lMGwh1ygSkr7/jZzuyRai0qKAxRyMp5p6QZ0bs9NEOJk1WRM5Co=,iv:NPFcThtj7zp7vtfekmtr7y5KHJHlxso8>sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-12T14:12:59Z"
    mac: ENC[AES256_GCM,data:uOvXe6AyrHza6b2TODbp+9PKcBTI8E3sfgbAh3E/DHq7cFpfF5y+reIAUdIb28OvhVbSmMRGBM4BvFSeuA7BMJnlcRqq7QtXFfV7R3QvazEKGuSJrzxBe2VxQ5J6bI1Szkknh/>    pgp:
        - created_at: "2021-08-12T14:12:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0tnhMOz2HWoAQwAivDmONugdeAd0Eh4CMt/YWuG6QfJm7PsGiyvVS3Pth+V
            VnivcsVVlHVGWe2YmAZ57N+OmpU+1yTJPvtnbVLyWZx7w1acQJ69RPiEu4wk1wNS
            7PL0I7F43dq+2tqjJ2u3HWL0JWQLbrUbcWTZQqI38KV6OwJw7GoWpvpGbaASwBwX
            FYykDfPG88xPs8/dYYTtzsAPj6znlGu4iso+wGwikMi4jKKo1InDawmAiyg+8keN
            8AaT8EXrmtxbfJBSt6FQv1pldbI0iNvyuGLnsJkf5sJuhloPCybVH1prPmN6zZlV
            ZKbi//FsN07nNCd5nhfMRPH9oA0eZIDVRf7J/GBaOoPTdbXrhy/Uz22+Eae08KSM
            gNdf13qvH/79ym4ZigEjUsqpvXgRVOU3tBVXbM5tUIi5RwZllpv3OYTIR1eyPJ54
            W0qyowqlnHBGOTVJVPK6NeZFxIi8A546Td/5dUgCCSsKjDIYUTNLAXsh/3JD+5Fy
            9lVWZ2TrgG2XQh3P2Gjf0l4BGkePQr+9eAFZCLLKakg1Kz6HtrhxSjC24r48Op+e
            u9N/ck/Kj8qiTIK3OrEFnJTreQ7hxiKnA3HZFD3HbJS8Dww4eYkOlOsZBlaoy3Zn
            HQsj52EPiuTyw7+Jg9M9
            =ub5X
            -----END PGP MESSAGE-----
          fp: 6C3E76432EC729C9A9D5DF9BF6D1BAF4117871B5
    unencrypted_suffix: _unencrypted
    version: 3.7.1
