replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "300m"
    memory: "800Mi"
  limits:
    cpu: "300m"
    memory: "800Mi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 30Gi
