apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: bee42/whoami:2.2.0
          ports:
          - containerPort: 80
            name: web
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 150Mi
